---
settings:
  name: ONTAP FLI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos FLI de ONTAP
    url: "/index.html"
  - section: san-migration
  - title: Avisos legales
    url: "/reference_legal_notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
