---
permalink: phases/plan-prepare-phase.html 
sidebar: sidebar 
keywords: plan and prepare phase, foreign lun import, fli, migration planning, test migration, cutover, intercluster lif, iscsi fli, gap analysis, san migration, fc fli, zoning, test migration 
summary: Ejecuta una o varias migraciones de prueba para confirmar que las cabinas, la red y la estructura, la configuración de ONTAP y los pasos de remediación del host son correctos, y para recopilar muestras de rendimiento que puedan extrapolarse para la programación de producción. 
---
= ONTAP Foreign LUN Import (FLI) migración de prueba y planificación de la transición
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ejecuta una o varias migraciones de prueba para confirmar que las cabinas, la red y la estructura, la configuración de ONTAP y los pasos de remediación del host son correctos, y para recopilar muestras de rendimiento que puedan extrapolarse para la programación de producción.

Una buena migración de prueba valida:

* Preparación del backend: la accesibilidad IC LIF, la estabilidad de las sesiones iSCSI y el descubrimiento de LUN ajenos es consistente en todas las rutas.
* Corrección del flujo de trabajo: la creación/inicio/visualización/completado (y verificación opcional) de relaciones de importación se comporta como se espera en el modo seleccionado (online/offline).
* Preparación del host: los pasos de rescaneo/remediación del host funcionan de forma fiable para el caso de uso objetivo (por ejemplo, ESXi VMFS/RDM, Windows standalone/WFC).
* Estimaciones operativas: el rendimiento observado en las pruebas proporciona la base más realista para estimar la duración de la migración a producción y suele ser mejor que cualquier referencia genérica.




== Probar el ejemplo de migración con Hitachi AMS2100

A continuación se muestra un ejemplo de migración de prueba utilizando un Hitachi AMS2100 como matriz externa. Según las cabinas involucradas, los sistemas operativos host y otras variables, los pasos pueden ser diferentes.

Puede utilizar el siguiente ejemplo como guía general de los pasos necesarios para realizar migraciones de prueba. NetApp recomienda realizar migraciones de pruebas lo antes posible para encontrar y reducir el tiempo necesario para resolver los problemas derivados de las pruebas. Se debe realizar una migración de pruebas en todas las combinaciones de cabinas de origen y destino antes de continuar con las migraciones de producción.

.Pasos
. Cree un LUN de prueba de 2 GB en la cabina de origen.
+
.. Inicia sesión en Hitachi Storage Navigator Modular como `system`.
.. Selecciona *AMS 2100 array*.
.. Haga clic en *Mostrar y configurar matriz*.
.. Inicia sesión usando `root`.
.. Expanda *grupos* y seleccione *unidades lógicas*.
.. Seleccione *Crear LU* para crear la LUN de prueba.
.. Cree un LUN de prueba de 2 GB.
.. Haga clic en *Aceptar*.
.. Omita aquí la asignación de LUN y haga clic en *Cerrar*.
.. Verifica que se haya creado el LUN de prueba.


. Asigna el LUN de prueba al grupo de hosts creado para los iniciadores ONTAP.
+
.. Expanda *grupos* y seleccione *unidades lógicas*.
.. Selecciona *Host Groups* para asignar el LUN de prueba al grupo de host *cDOT_FLI*.
.. Selecciona el grupo de hosts *cDOT_FLI* creado en el paso anterior y haz clic en *Editar grupo de hosts*.
.. Elige los puertos para el grupo de host. En este ejemplo elegimos *0a*, *0e*, *1a*, *1e*. Selecciona la opción *Forced Set to All Selected Ports*.
.. En HDS Storage Navigator, edita el grupo de hosts.
.. Haz clic en *Logical Units* y añade el LUN de prueba.
.. Haga clic en *Aceptar* para asignar la LUN.
.. Seleccione *Sí, he leído la advertencia anterior y deseo editar el grupo de hosts* y haga clic en *Confirmar*.
.. Compruebe la creación del grupo de hosts y haga clic en *Cerrar*.


. Verifique la LUN de prueba y la asignación desde el almacenamiento de origen al almacenamiento de destino, y ejecute la importación de LUN externa (FLI).
+
.. Inicia sesión en el almacenamiento ONTAP a través de SSH usando el usuario `admin`.
.. Cambia el modo a *Avanzado*.
+
DataMig-cmode::> set -privilege advanced

.. Introduce "y" cuando se te pregunte si quieres continuar con los comandos avanzados.
.. Descubra la matriz de origen en ONTAP. Espere unos minutos y vuelva a intentar detectarla.
+
mostrar matriz de almacenamiento

+
Cuando se detecta la cabina de almacenamiento por primera vez, es posible que ONTAP no muestre la cabina mediante la detección automática. Use las siguientes instrucciones para restablecer el puerto del switch donde están conectados los puertos iniciadores de ONTAP.

+
Por ejemplo, los puertos iniciadores del clúster DataMig-cmode `0a` y `0b` de ONTAP están conectados a los puertos de Cisco `4/9` y `4/11`. Para reiniciar el puerto `4/9` en el switch Cisco:

+
[listing]
----
conf t
interface fc4/
shutdown
no shutdown
exit
exit
----
+
Restablecer un puerto por lo general es suficiente. Compruebe la lista de cabinas y las rutas de LUN después de restablecer un puerto.

.. Verifica que el array de origen se descubre a través de todos los puertos iniciadores:
+
storage array config show -array-name HITACHI_DF600F_1

+
[listing]
----
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-cmode-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-cmode-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----
.. Enumera el LUN de prueba asignado desde el almacenamiento Hitachi y verifica las propiedades y rutas del disco:
+
storage disk show -array-name HITACHI_DF600F_1 -instance

+
[listing]
----

                  Disk: HIT-1.1
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: HITACHI_DF600F_1
                Vendor: HITACHI
                 Model: DF600F
         Serial Number: 83017542001A
                   UID: 48495441:43484920:38333031:37353432:30303236:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                                LUN  Initiator Side        Target Side                                            Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port     TPGN    Speed  I/O KB/s  IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  --------------  ------  ----   --- -----
DataMig-cmode-01   0a             0  DM-Cisco9506-1:4-9    DM-Cisco9506-1:2-24   AO  INU  50060e801046b968  2   2 Gb/S    0  0
DataMig-cmode-01   0b             0  DM-Cisco9506-2:4-9    DM-Cisco9506-2:2-24   AO  INU  50060e801046b96c  2   2 Gb/S    0  0
DataMig-cmode-01   0b             0  DM-Cisco9506-2:4-9    DM-Cisco9506-2:1-14   AO  INU  50060e801046b964  1   2 Gb/S    0  0
DataMig-cmode-01   0a             0  DM-Cisco9506-1:4-9    DM-Cisco9506-1:1-14   AO  INU  50060e801046b960  1   2 Gb/S    0  0
DataMig-cmode-02   0a             0  DM-Cisco9506-1:4-11   DM-Cisco9506-1:2-24   AO  INU  50060e801046b968  2   2 Gb/S    0  0
DataMig-cmode-02   0b             0  DM-Cisco9506-2:4-11   DM-Cisco9506-2:2-24   AO  INU  50060e801046b96c  2   2 Gb/S    0  0
DataMig-cmode-02   0b             0  DM-Cisco9506-2:4-11   DM-Cisco9506-2:1-14   AO  INU  50060e801046b964  1   2 Gb/S    0  0
DataMig-cmode-02   0a             0  DM-Cisco9506-1:4-11   DM-Cisco9506-1:1-14   AO  INU  50060e801046b960  1   2 Gb/S    0  0

Errors:
-

DataMig-cmode::*>
----


. Marca el LUN de origen como ajeno utilizando el número de serie:
+
storage disk set-foreign-lun { -serial-number 83017542001A } -is-foreign true

+
.. Verifica que el LUN de origen esté marcado como externo:
+
storage disk show -array-name HITACHI_DF600F_1

.. Lista todas las matrices extranjeras y sus números de serie:
+
storage disk show -container-type foreign -fields serial-number

+

NOTE: El comando LUN create detecta el tamaño y la alineación basados en la separación de particiones y crea el LUN en consecuencia con el argumento Foreign Disk.



. Crear un volumen de destino:
+
vol create -vserver datamig flivol aggr1 -size 10g

. Crea un LUN de prueba usando un LUN ajeno:
+
lun create -vserver datamig -path /vol/flivol/testlun1 -ostype linux -foreign-disk 83017542001A

+
.. Enumera el LUN de prueba y verifica el tamaño del LUN con el LUN de origen:
+
lun show

+

NOTE: Para la migración sin conexión FLI, la LUN debe estar en línea para asignarla a un igroup y, luego, debe estar sin conexión antes de crear la relación de importación de LUN.



. Crear igrupo de prueba de protocolo FCP sin añadir ningún iniciador:
+
lun igroup create -vserver datamig -igroup testig1 -protocol fcp -ostype linux

. Asigna el LUN de prueba al igroup de prueba:
+
lun map -vserver datamig -path /vol/flivol/testlun1 -igroup testig1

. Desconecta el LUN de prueba:
+
lun offline -vserver datamig -path /vol/flivol/testlun1

. Crea una relación de importación con el LUN de prueba y el LUN externo:
+
lun import create -vserver datamig -path /vol/flivol/testlun1 -foreign-disk 83017542001A

. Inicia la migración (importación):
+
lun import start -vserver datamig -path /vol/flivol/testlun1

+
.. Supervisa el progreso de la importación:
+
lun import show -vserver datamig -path /vol/flivol/testlun1

.. Comprueba que el trabajo de importación se ha completado correctamente:
+
lun import show -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           import    started
                                                           completed     100
----


. Inicia el trabajo de verificación para comparar los LUN de origen y destino. Supervisa el progreso de la verificación:
+
lun import verify start -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
DataMig-cmode::*> lun import show -vserver datamig -path /vol/flivol/testlun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           verify    started
                                                           in_progress     44
----
+
.. Comprueba que el trabajo de verificación se ha completado sin errores:
+
lun import show -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           verify    started
                                                           completed      100
----


. Elimina la relación de importación para quitar el trabajo de migración:
+
lun import delete -vserver datamig -path /vol/flivol/testlun1

+
lun import show -vserver datamig -path /vol/flivol/testlun1

. Desasigna el LUN de prueba del igroup de prueba:
+
lun unmap -vserver datamig -path /vol/flivol/testlun1 -igroup testig1

. En línea el LUN de prueba:
+
lun online -vserver datamig -path /vol/flivol/testlun1

. Marca el atributo LUN externo como falso:
+
storage disk modify -serial-number 83017542001A -is-foreign false

+

NOTE: No quite el grupo de hosts creado en almacenamiento de origen con puertos iniciadores ONTAP. El mismo grupo de hosts se vuelve a utilizar durante las migraciones de esa cabina de origen.

. Quitar la LUN de prueba del almacenamiento origen.
+
.. Inicie sesión en Hitachi Storage Navigator Modular como sistema.
.. Selecciona *AMS 2100 array* y haz clic en *Show and Configure Array*.
.. Inicia sesión usando `root`.
.. Seleccione *grupos* y, a continuación, seleccione *grupos de host*.
.. Selecciona *cDOT_FLI Igroup* y haz clic en *Edit Host Group*.
.. En la ventana Edit Host Group, selecciona todos los puertos de destino elegidos para asignar el LUN de prueba y selecciona *Forced Set to All Selected Ports*.
.. Seleccione la ficha *unidades lógicas*.
.. Seleccione el LUN de prueba en la ventana *unidades lógicas asignadas*.
.. Seleccione *Quitar* para eliminar la asignación de LUN.
.. Haga clic en *Aceptar*.


. No quite el grupo de hosts y continúe eliminando el LUN de prueba.
+
.. Selecciona *Unidades lógicas*.
.. Selecciona el LUN de prueba creado en el paso anterior.
.. Haga clic en *Eliminar LUN*.
.. Haga clic en *Confirmar* para eliminar el LUN de prueba.


. Eliminar la LUN de prueba del almacenamiento de destino.
+
.. Inicia sesión en el almacenamiento ONTAP a través de SSH usando el usuario `admin`.
.. Desconecta el LUN de prueba en el sistema de almacenamiento NetApp:
+
lun offline -vserver datamig -path /vol/flivol/testlun1

+

NOTE: Asegúrese de no seleccionar otro LUN de host.

.. Destruye el LUN de prueba en el sistema de almacenamiento NetApp:
+
lun destroy -vserver datamig -path /vol/flivol/testlun1

.. Desconecta el volumen de prueba en el sistema de almacenamiento NetApp:
+
vol offline -vserver datamig -volume flivol

.. Destruye el volumen de prueba en el sistema de almacenamiento NetApp:
+
vol destroy -vserver datamig -volume flivol




