---
permalink: san-migration/concept_using_fli_to_import_luns_into_all_flash.html 
sidebar: sidebar 
keywords: use, foreign lun import, import luns, aff 
summary: A partir de ONTAP 9.1, AFF admite FLI. Puede utilizar FLI para importar LUN desde otras matrices directamente a clústeres ONTAP . 
---
= Uso de la importación de LUN externos para importar LUN a AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.1, AFF admite FLI. Puede utilizar FLI para importar LUN desde otras matrices directamente a clústeres ONTAP .

A partir de ONTAP 8.3.2, AFF puede respaldar FLI con una solicitud de variación de proceso (PVR) aprobada. Comuníquese con su equipo de cuenta de NetApp para enviar el PVR para su aprobación. Tras la aprobación, el remitente, generalmente un ingeniero de sistemas de NetApp , recibirá una carta de aprobación con instrucciones para habilitar la funcionalidad FLI.

Para las versiones del software ONTAP anteriores a 8.3.2, deberá preparar las importaciones de FLI en un par HA que no sea AFF en el mismo clúster que AFF. Una vez completada la migración, puede utilizar operaciones no disruptivas (NDO), como vol o LUN move, para mover los LUN migrados a AFF. Si su clúster AFF no tiene ningún nodo que no sea AFF , hable con su equipo de cuentas sobre la posibilidad de pedir prestado equipo Swing para facilitar esto.
