---
permalink: san-migration/concept_7_mode_to_ontap_supported_configurations.html 
sidebar: sidebar 
keywords: 7-mode, ontap, fli, supported, configurations 
summary: Es importante verificar que el sistema operativo host, el HBA, el switch y la cabina de ONTAP a la que, en última instancia, se admite la transición. 
---
= Configuraciones compatibles de 7-Mode a ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es importante verificar que el sistema operativo host, el HBA, el switch y la cabina de ONTAP a la que, en última instancia, se admite la transición.

Si está utilizando el flujo de trabajo de transición de FLI 7-Mode a ONTAP , no necesita verificar su fuente (controlador 7-Mode) en el IMT. No aparecerá en la lista, pero se admite expresamente para este flujo de trabajo de transición. Aún es necesario verificar que todos los hosts tengan una configuración compatible.

No existen requisitos específicos de la plataforma FLI. Además, no hay versiones mínimas de Data ONTAP en 7-Mode, aunque la versión debe ser compatible con el protocolo Fibre Channel (FCP).

El tamaño máximo del LUN que FLI puede importar es de 6 TB. Esta es una limitación basada en el tamaño máximo actual de unidades compatibles actualmente con ONTAP. Si se intenta montar una LUN externa más grande, la LUN se marcará como rota y no se podrá escribir una etiqueta en ella.
