---
permalink: san-migration/concept_performance_enhancements_in_clustered_data_ontap_8_3_1.html 
sidebar: sidebar 
keywords: performance, enhancements, ontap 8.3.1 
summary: Se han aplicado algunas mejoras a FLI para gestionar mejor el rendimiento y evitar que se produzca una inanición en la carga de trabajo. Las mejoras de FLI en ONTAP 8.3.1 incluyen un nuevo comando acelerador y la importación de LUN muestran mejoras que muestran el rendimiento y los grupos de políticas de calidad de servicio. 
---
= Mejoras del rendimiento en ONTAP 8.3.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se han aplicado algunas mejoras a FLI para gestionar mejor el rendimiento y evitar que se produzca una inanición en la carga de trabajo. Las mejoras de FLI en ONTAP 8.3.1 incluyen un nuevo comando acelerador y la importación de LUN muestran mejoras que muestran el rendimiento y los grupos de políticas de calidad de servicio.

La `LUN import throttle` el comando se utiliza para limitar la velocidad máxima a la que se puede ejecutar una importación.

[listing]
----
cluster::*> lun import throttle -vserver fli_72C -path /vol/flivol/72Clun1 -max-throughput-limit

{<integer>[KB|MB|GB|TB|PB]}  Maximum Throughput Limit (per sec)
----
Utilice la `instance` cambie con `lun import show` Para mostrar información ampliada de importación de LUN, incluida la información de aceleración y calidad de servicio.

[listing]
----
cluster::*> lun import show -instance

    Vserver Name: fli_72C
    LUN Path: /vol/flivol/72Clun1
    Foreign Disk Serial Number: D0i1E+G8Wg6m
    Import Home Node: ontaptme-fc-cluster-01
    Import Current Node: ontaptme-fc-cluster-01
    Operation In Progress: import
    Admin State: stopped
    Operational State: stopped
    Percent Complete: 0
    Blocks Imported: -
    Blocks Compared: -
    Total Blocks: 6297480
    Estimated Remaining Duration: -
    Failure Reason: -
    Maximum Throughput Limit(per sec): -
    Current Throughput (per sec): -
    QoS Policy Group: -
----
Los valores para `current throughput` muestra la tasa actual de rendimiento de las operaciones de importación o verificación. Los usuarios deben comprobarlo antes de ajustar el valor de aceleración. Está vacío cuando no se está ejecutando. La `QoS policy group` Muestra el grupo QoS si se utilizó la aceleración de importación de la LUN.
