---
permalink: san-migration/concept_lun_requirements_and_limitations.html 
sidebar: sidebar 
keywords: lun, requirements, limitations 
summary: Sus LUN deben cumplir con los siguientes requisitos antes de iniciar la migración FLI. 
---
= Requisitos y limitaciones de LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sus LUN deben cumplir con los siguientes requisitos antes de iniciar la migración FLI.

* FLI requiere al menos un puerto FC en cada controladora y para que las LUN migren directamente en modo iniciador.
* El LUN externo debe marcarse como externo en la matriz de destino para evitar asignaciones desde ONTAP.
* El LUN extranjero debe estar en una relación de importación antes de iniciar la importación.
* El LUN debe tener el mismo tamaño que el LUN externo. Este requisito se atiende durante los pasos de creación del LUN.
* El tamaño del bloque LUN externo debe ser 512b. Los LUN de NetApp solo admiten un tamaño de bloque de 512 b.
* La LUN no debe ampliarse ni contraerse.
* La LUN debe asignarse al menos a un igroup.
* El LUN de NetApp debe desconectarse antes de crear una relación. Sin embargo, una vez creada la relación LUN, es posible volver a ponerla en línea en caso de FLI en línea.




== Limitaciones

* Todas las migraciones se encuentran en el nivel de LUN.
* FLI solo admite conexiones de Fibre Channel (FC).
* FLI no admite conexiones iSCSI directamente. Para que los LUN de iSCSI se migren con FLI, el tipo de LUN debe cambiarse por FC. Una vez finalizada la migración, el tipo de LUN se vuelve a cambiar a iSCSI.

