---
permalink: san-migration/concept_fli_zoning_requirements.html 
sidebar: sidebar 
keywords: fli, zoning, requirements 
summary: Una situación de migración estándar con FLI requiere cuatro zonas distintas. Debe incluir puertos específicos en cada zona. 
---
= Requisitos de la división en zonas de FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una situación de migración estándar con FLI requiere cuatro zonas distintas. Debe incluir puertos específicos en cada zona.

* Zona 1: Almacenamiento de origen a almacenamiento de destino (estructura De producción A)
+
La zona 1 debe contener todos los iniciadores de almacenamiento de destino en todos los nodos y todos los puertos de destino de almacenamiento de origen de la estructura A. Entre los miembros de la zona se incluyen:

+
** ONTAP -- Nodo1 -- 0a
** ONTAP -- Nodo2 -- 0a
** AMS2100 -- Ctrl0 -- 0a
** AMS2100 -- CTRL1 -- 1a


* Zona 2: Almacenamiento de origen al almacenamiento de destino (estructura de producción B)
+
La zona 2 debe contener todos los puertos de iniciadores de almacenamiento de destino en todos los nodos y todos los puertos de destino de almacenamiento de origen de la estructura B. Entre los miembros de la zona 2 se incluyen:

+
** ONTAP -- Nodo1 -- 0b
** ONTAP -- Nodo2 -- 0b
** AMS2100 -- Ctrl0 -- 0e
** AMS2100 -- CTRL1 -- 1e


* Zona 3: Host a almacenamiento de destino (estructura De producción A)
+
La zona 3 debe contener el puerto 1 del adaptador de bus de host (HBA) y los puertos de la controladora de destino en la estructura de producción A. Entre los miembros de la zona 3 se incluyen:

+
** ONTAP -- lif1
** ONTAP -- lif3
** Host -- HBA0


* Zona 4: Host a almacenamiento de destino (estructura de producción B)
+
La zona 4 debe contener el puerto HBA 2 y los puertos de la controladora de destino en la estructura de producción B. Entre los miembros de la zona 4 se incluyen:

+
** ONTAP -- lif2
** ONTAP -- lif4
** Host -- HBA1



