---
permalink: san-migration/reference_site_survey_and_planning_worksheet_netapp_lun_layouts_tab.html 
sidebar: sidebar 
keywords: site, survey and planning worksheet, netapp lun layouts tab 
summary: Como parte de la hoja de trabajo para realizar una encuesta y planificación del sitio, debe configurar una pestaña que contenga información sobre los diseños de LUN. 
---
= Hoja de trabajo para la encuesta y la planificación del sitio Ficha diseños de LUN de NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como parte de la hoja de trabajo para realizar una encuesta y planificación del sitio, debe configurar una pestaña que contenga información sobre los diseños de LUN.

A continuación figura un ejemplo de cómo configurar la pestaña diseños de LUN de NetApp.

|===
7+| Información de LUN de NetApp 


 a| 
Controladora de almacenamiento
 a| 
Agregado
 a| 
Nombre del volumen
 a| 
Tamaño del volumen
 a| 
Garantía de volumen
 a| 
Reserva Snap
 a| 
Nombre de LUN

|===
|===
7+| Información de LUN de NetApp 


 a| 
S/N
 a| 
Tipo de LUN
 a| 
Prefijo personalizado
 a| 
Descripción de LUN
 a| 
Tamaño en GB
 a| 
Reserva de LUN
 a| 
Reserva fraccionaria

|===
|===
7+| Información de LUN de NetApp 


 a| 
Tamaño automático del volumen
 a| 
Eliminación automática de snap
 a| 
IGroup
 a| 
ID DE LUN
 a| 
Tipo de host
 a| 
Letra de unidad
 a| 
Host

|===