---
permalink: san-migration/remove-lun-import-relationship-offline.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: Un trabajo de verificación es opcional, pero se recomienda. Es una comparación entre bloques de las LUN de origen y de destino. La verificación de las tareas tarda casi el mismo tiempo, o incluso un poco más, que el tiempo de migración. 
---
= Eliminar la relación de importación de LUN después de una migración sin conexión de ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una vez completada la migración sin conexión de la Importación de LUN Externos (FLI), la relación de importación de LUN se puede eliminar de forma segura. El host ahora accede a la nueva matriz NetApp para todas las E/S al nuevo LUN de ONTAP y el LUN de origen ya no se utiliza, por lo que la relación de importación ya no es necesaria.

A partir de ONTAP 9.17.1, la migración de datos de LUNs ajenos mediante migración FLI offline es compatible conlink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Sistemas ASA r2"^]. Los sistemas ASA r2 se diferencian de otros sistemas ONTAP (ASA, AFF y FAS) en la implementación de su capa de almacenamiento. de nombres). Cada volumen contiene solo una unidad de almacenamiento. Por lo tanto, en los sistemas ASA r2, no es necesario incluir el nombre del volumen en el...  `-path` opción al crear el LUN; debe incluir la ruta de la unidad de almacenamiento en su lugar.

.Pasos
. Eliminar la relación de importación para eliminar los trabajos de importación de datos.
+
[source, cli]
----
lun import delete -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Este ejemplo muestra el comando para eliminar la relación de importación de los LUN denominados *bootlun*, *fdrive* y *gdrive* en el volumen *winvol* y la SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/gdrive
----
. Verifique que los trabajos de importación se hayan eliminado.
+
[source, cli]
----
lun import show -vserver <SVM_name>
----
+
Este ejemplo muestra el comando para verificar que se eliminen los trabajos de importación para el SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig
There are no entries matching your query.
----
. Marque el atributo de LUN externa como `false`.
+
[source, cli]
----
storage disk modify -serial-number <serial_number> -is-foreign false
----
+
Este ejemplo muestra el comando para marcar el atributo LUN externo a  `false` para los LUN denominados *bootlun*, *fdrive* y *gdrive* en el volumen *winvol* y el SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> storage disk modify { -serial-number 83017542001E }
-is-foreign false

DataMig-ontap::*> storage disk modify { -serial-number 83017542000E }
-is-foreign false

DataMig-ontap::*> storage disk modify { -serial-number 83017542000F }
-is-foreign false
----
. Verifique que los LUN externos estén marcados como  `false` .
+
[source, cli]
----
storage disk show -array-name <array_name> -fields disk, serial-number, container-type, owner, import-in-progress, is-foreign
----
+
Este ejemplo muestra el comando para verificar que los LUN externos estén marcados como  `false` en la matriz *HITACHI_DF600F_1*.

+
[listing]
----
DataMig-ontap::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign

disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     false      unassigned     false              83017542001E
HIT-1.3  -     false      unassigned     false              83017542000E
HIT-1.4  -     false      unassigned     false              83017542000F
3 entries were displayed.
----
. Ponga en línea los LUN de destino.
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Este ejemplo muestra el comando para poner en línea los LUN de destino para los LUN denominados *bootlun*, *fdrive* y *gdrive* en el volumen *winvol* y la SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/gdrive
----
. Compruebe que las LUN están en línea.
+
[source, cli]
----
lun show -vserver <SVM_name>
----
+
Este ejemplo muestra el comando para verificar que los LUN estén en línea para el SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun show -vserver datamig
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  mapped   vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  mapped   linux         2GB
datamig   /vol/esxvol/solrdmplun          online  mapped   solaris       2GB
3 entries were displayed.
----
. Opcionalmente, vea el registro de eventos para verificar los resultados de la migración.
+
[source, cli]
----
event log show –event fli*
----
+
Este ejemplo muestra la salida de muestra del comando para ver el registro de eventos para los resultados de la migración de FLI.

+
[listing]
----
DataMig-ontap::*> event log  show –event fli*

7/7/2014 18:37:21   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 83017542001E of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiS is successfully completed.
7/7/2014 18:37:15   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 830175420015 of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiX is successfully completed.
7/7/2014 18:02:21   DataMig-ontap-01 INFORMATIONAL fli.lun.import.complete: Import of foreign LUN 83017542000F of size 3221225472 bytes from array model DF600F belonging to vendor HITACHI  is successfully completed. Destination NetApp LUN is QvChd+EUXoiU.
----


.¿Que sigue?
link:concept_fli_offline_post_migration_tasks.html["Realizar tareas posteriores a la migración para una migración fuera de línea de FLI"] .
