---
permalink: san-migration/task_fli_offline_importing_the_data.html 
sidebar: sidebar 
keywords: fli offline, import data 
summary: Estos pasos describen cómo importar los datos de la LUN de origen a la LUN de destino. 
---
= FLI sin conexión: Importe los datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Estos pasos describen cómo importar los datos de la LUN de origen a la LUN de destino.

.Pasos
. Inicie la importación de la migración.
+
[listing]
----
DataMig-cmode::*> lun import start –vserver datamig –path /vol/winvol/bootlun

DataMig-cmode::*> lun import start –vserver datamig –path /vol/winvol/fdrive

DataMig-cmode::*> lun import start –vserver datamig –path /vol/winvol/gdrive
----
. Supervise el progreso de la importación. Puede comparar el progreso que ve aquí con las estimaciones de rendimiento de la migración que ha desarrollado tras realizar las migraciones de prueba.
+
[listing]
----
DataMig-cmode::*> lun import show –vserver datamig –fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     completed         100              4194304         4194304      -
datamig 83017542000F /vol/winvol/gdrive started     completed         100              6291456         6291456      -
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       83               35107077        41943040     00:00:48
3 entries were displayed.
----
. Compruebe que el trabajo de importación se ha completado correctamente.
+
[listing]
----
DataMig-cmode::*> lun import show –vserver datamig –fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     completed         100              4194304         4194304      -
datamig 83017542000F /vol/winvol/gdrive started     completed         100              6291456         6291456      -
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     completed         100
3 entries were displayed.
----

