---
permalink: san-migration/task_fli_online_preparing_the_lun_path.html 
sidebar: sidebar 
keywords: fli online, prepare, lun path 
summary: Para preparar la migración en línea FLI, debe verificar las rutas de LUN de host y de origen, así como otros detalles. 
---
= FLI en línea: Preparar la ruta de la LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para preparar la migración en línea FLI, debe verificar las rutas de LUN de host y de origen, así como otros detalles.

.Pasos
. En ONTAP, cambie el nivel de privilegio a. `advanced`.
+
[listing]
----
cluster::> set adv

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y
----
. Verifique que la cabina de origen se pueda ver en la controladora de destino.
+
[listing]
----

        cluster::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
DGC-1                      DGC_LUNZ_1      DGC             LUNZ
1 entries were displayed.
----
. Mostrar detalles de la LUN de origen.
+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1 -instance

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601643ea067da
                 Initiator: 0c
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-3:2-1
Initiator Side Switch Port: stme-5010-3:2-3
      Number of array LUNs: 1

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601653ea067da
                 Initiator: 0d
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-4:2-1
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 1
~~~~~~~~~~~ output truncated for readability ~~~~~~~~~~~~~~~~~
8 entries were displayed.
----
. Verifique que la cabina de origen se haya detectado a través de todos los puertos iniciadores.
+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
ontaptme-fc-cluster-02
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
8 entries were displayed.
----
+
[NOTE]
====
El ajuste de palabras en la siguiente salida no tiene ningún significado.

====
. Enumere las LUN asignadas del almacenamiento de origen. Compruebe las propiedades y rutas del disco.
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1 -instance
                  Disk: DGC-1.9
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: DGC_LUNZ_1
                Vendor: DGC
                 Model: VRAID
         Serial Number: 600601603F103100662E70861000E511
                   UID: 60060160:3F103100:662E7086:1000E511:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                               LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
ontaptme-fc-cluster-02
                   0c             0  stme-5010-3:2-4       stme-5010-3:2-2       AO  INU  5006016c3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-2       AO  INU  5006016d3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-1       ANO RDY  500601653ea067da              1   4 Gb/S             0             0

Errors:
-
----
. Vea la LUN de origen.
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9                   -     -   - LUN     unassigned  -         -
----
. Marque la LUN de origen como externa.
+
[listing]
----
cluster::*> storage disk set-foreign-lun -is-foreign true -disk DGC-1.9
----
. Compruebe que la LUN de origen esté marcada como externa.
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9
----
. Los números de serie se usan en los comandos de importación de la LUN FLI. Enumere todas las LUN externas y sus números de serie.
+
[listing]
----
cluster::*> storage disk show -container-type foreign -fields serial-number
disk    serial-number
------- --------------------------------
DGC-1.9 600601603F103100662E70861000E511
----
. Crear un volumen de destino.
+
[listing]
----
cluster::*> vol create -vserver fli -volume fli_vol -aggregate aggr1 -size 2t
[Job 13888] Job succeeded: Successful
----
. Verificar volumen.
+
[listing]
----
cluster::*> vol show -vserver fli
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
fli       fli_root     aggr1        online     RW          1GB    972.6MB    5%
fli       fli_vol      aggr1        online     RW          2TB     1.90TB    5%
2 entries were displayed.
----
. Establezca la opción fraction_reserveOption para cada volumen en `0` Y establezca la política de Snapshot en `none`.
+
[listing]
----
cluster::*> vol modify -vserver datamig -volume * -fractional-reserve 0 –snapshot-policy none
Volume modify successful on volume winvol of Vserver datamig.
----
. Compruebe la configuración del volumen.
+
[listing]
----
cluster::*> vol show -vserver datamig -volume * -fields fractional-reserve,snapshot-policy
vservervolumesnapshot-policyfractional-reserve
-----------------------------------------------
datamigdatamig_rootnone0%
datamigwinvolnone0%
Volume modify successful on volume winvol of Vserver datamig.
----
. Elimine las copias Snapshot existentes.
+
[listing]
----
cluster::*> set advanced; snap delete –vserver datamig –vol winvol –snapshot * -force true
1 entry was acted on.
----
+
[NOTE]
====
La migración FLI modifica cada bloque de las LUN de destino. Si hay valores predeterminados u otras copias Snapshot en un volumen antes de la migración FLI, se llenará el volumen. Es necesario cambiar la política y eliminar todas las copias Snapshot existentes antes de que se requiera la migración FLI. La política de Snapshot se puede establecer de nuevo después de la migración.

====
+
[NOTE]
====
El comando LUN create detecta el tamaño y la alineación basados en la separación de particiones y crea el LUN en consecuencia con la opción «disco externo». Para revisar el estado de alineación incorrecta de I/o, consulte el artículo de la base de conocimientos de NetApp * ¿Qué es un I/o * sin alinear? Tenga en cuenta también que algunas I/o siempre aparecerán con escrituras parciales y, por lo tanto, quedarán mal alineadas. Ejemplos de esto serían los registros de la base de datos.

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F["¿Qué es una I/o no alineada?"]

. Cree la LUN de destino. La `LUN create` El comando detecta el tamaño y la alineación basados en la compensación de particiones y crea la LUN de manera acorde con el argumento Foreign-disk.
+
[listing]
----
cluster::*> lun create -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -ostype windows_2008 -foreign-disk 600601603F103100662E70861000E511

Created a LUN of size 1t (1099511627776)
----
. Verificar la nueva LUN.
+
[listing]
----
cluster::*> lun show -vserver fli
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli       /vol/fli_vol/OnlineFLI_LUN      online  unmapped windows_2008  1TB
----
. Cree un igroup de protocolo FCP con iniciadores de host.
+
[listing]
----
cluster::*> igroup create -vserver fli -igroup FLI -protocol fcp -ostype windows -initiator 10:00:00:00:c9:e6:e2:79
----
. Compruebe que el host inicia sesión en todas las rutas al nuevo igroup.
+
[listing]
----
cluster::*> igroup show –vserver fli –igroup FLI
   Vserver name: fli
    Igroup name: FLI
       Protocol: fcp
     OS Type: Windows
Portset Binding Igroup: -
   Igroup UUID: 5c664f48-0017-11e5-877f-00a0981cc318
          ALUA: true
    Initiators: 10:00:00:00:c9:e6:e2:77 (logged in)
10:00:00:00:c9:e6:e2:79 (logged in)
----
. Desconecte la LUN de destino.
+
[listing]
----
cluster::*> lun offline -vserver fli -path /vol/fli_vol/OnlineFLI_LUN

Warning: This command will take LUN "/vol/fli_vol/OnlineFLI_LUN" in Vserver "fli" offline.
Do you want to continue? {y|n}: y
----
. Asigne la LUN de destino al igroup.
+
[listing]
----
cluster::*> lun map -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -igroup FLI
----
. Crear relación de importación entre la nueva LUN y la LUN externa.
+
[listing]
----
cluster::*> lun import create -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -foreign-disk 600601603F103100662E70861000E511
----

