---
permalink: san-migration/task_verifying_source_luns_on_destination_storage_for_offline_foreign_lun_import.html 
sidebar: sidebar 
keywords: verify, source luns, destination storage, offline fli 
summary: Como parte del proceso de importación de LUN externa sin conexión, debe comprobar sus LUN de origen en el almacenamiento de destino. 
---
= Verificación de las LUN de origen en el almacenamiento de destino para FLI sin conexión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como parte del proceso de importación de LUN externa sin conexión, debe comprobar sus LUN de origen en el almacenamiento de destino.

.Pasos
. Compruebe las LUN de origen y la asignación desde el almacenamiento de origen al almacenamiento de destino.
. Inicie sesión en el almacenamiento de ONTAP a través de SSH mediante el usuario administrador.
. Cambie el modo a Avanzado: `set -privilege advanced`
. Introduzca `y` cuando se le pregunte si desea continuar.
. Detectar la cabina de origen en ONTAP. Se deben esperar unos minutos y volver a intentar detectar la cabina de origen. `storage array show`
+
[listing]
----
DataMig-cmode::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
HIT-1                HITACHI_DF600F_1  HITACHI           DF600F
----
+
[NOTE]
====
Cuando se detecta la cabina de almacenamiento por primera vez, es posible que ONTAP no muestre la cabina mediante la detección automática. Use las siguientes instrucciones para restablecer el puerto del switch donde están conectados los puertos iniciadores de ONTAP.

====
. Verifique que la cabina de origen se haya detectado a través de todos los puertos iniciadores.
+
[listing]
----
DataMig-cmode::*> storage array config show -array-name HITACHI_DF600F_1
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-cmode-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-cmode-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----
. Enumere las LUN de origen asignadas del almacenamiento de Hitachi. Compruebe las propiedades y rutas del disco.
+
Debe ver el número esperado de rutas según el cableado (al menos dos rutas para cada controladora de origen). También debe comprobar el registro de eventos después de enmascarar los LUN de cabina.

+
[listing]
----
DataMig-cmode::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner, path-lun-in-use-count, import-in-progress, is-foreign
disk     owner is-foreign container-type import-in-progress path-lun-in-use-count serial-number
-------- ----- ---------- -------------- ------------------ --------------------- -------------
HIT-1.2  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542001E
HIT-1.3  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542000E
HIT-1.14 -     false      unassigned     false        0,0,0,0,0,0,0,0       830175420019
3 entries were displayed.

DataMig-cmode::*>
----

