---
permalink: san-migration/task_fli_online_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli online, verify, migration, results 
summary: Un trabajo de verificación es opcional, pero se recomienda. Es una comparación entre bloques de las LUN de origen y de destino. La verificación de las tareas tarda casi el mismo tiempo, o incluso un poco más, que el tiempo de migración. 
---
= Verificar los resultados de la migración en línea de ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tras migrar su LUN del arreglo externo al arreglo ONTAP , la Importación de LUN Externos (FLI) puede realizar una comparación bloque por bloque de los LUN de origen y destino para verificar que la migración sea completa y precisa. La verificación de la migración tarda aproximadamente el mismo tiempo (o un poco más) que la migración.

No es necesaria una verificación de migración, pero es muy recomendable.

.Acerca de esta tarea
* A partir de ONTAP 9.17.1, la migración de datos de LUNs ajenos mediante migración FLI offline es compatible conlink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Sistemas ASA r2"^]. Los sistemas ASA r2 se diferencian de otros sistemas ONTAP (ASA, AFF y FAS) en la implementación de su capa de almacenamiento. de nombres). Cada volumen contiene solo una unidad de almacenamiento. Por lo tanto, en los sistemas ASA r2, no es necesario incluir el nombre del volumen en el...  `-path` opción al crear el LUN; debe incluir la ruta de la unidad de almacenamiento en su lugar.
* Una verificación de migración es disruptiva. Los LUN que se verifican deben estar desconectados durante la verificación.


.Pasos
. Sin conexión las LUN que se van a verificar.
+
[source, cli]
----
lun offline -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Este ejemplo muestra el comando para desconectar el LUN llamado *72Clun1* en el volumen *flivol* y el SVM *fli_72C*.

+
[listing]
----
cluster::*> lun offline -vserver fli_72C -path /vol/flivol/72Clun1
Warning: This command will take LUN "/vol/flivol/72Clun1" in Vserver "fli_72C" offline.
Do you want to continue? {y|n}: y
----
+
El periodo de interrupción comienza aquí.

. Iniciar la verificación de la migración de LUN.
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
. Supervisar el estado de verificación.
+
[source, cli]
----
lun import show -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Este ejemplo muestra el comando para monitorear el estado de verificación del LUN llamado *72Clun1* en el volumen *flivol* y el SVM *fli_72C*.

+
[listing]
----
ontaptme-fc-cluster::*> lun import show -vserver fli_72C -path /vol/flivol/72Clun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
fli_72C D0i1E+G8Wg6m   /vol/flivol/72Clun1 verify    started
                                                                        9
----
. Detener la verificación de LUN.
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
La verificación de importación de LUN debe detenerse explícitamente antes de volver a poner el LUN en línea. De lo contrario, el LUN fallará. Este paso debe realizarse manualmente incluso si el estado indica que la verificación se ha completado.

. En línea el LUN.
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
El plazo para la interrupción termina aquí.



.¿Que sigue?
link:remove-lun-import-relationship-online.html["Eliminar la relación de importación de LUN"] .
