---
permalink: san-migration/task_fli_transition_preparing_source_and_destination_arrays.html 
sidebar: sidebar 
keywords: prepare, source, destination, arrays, migration 
summary: Para preparar la migración FLI de 7-Mode a ONTAP, verifique las rutas de las LUN del host y de origen, así como otros detalles. 
---
= Preparación de cabinas de origen y de destino para la migración
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para preparar la migración FLI de 7-Mode a ONTAP, verifique las rutas de las LUN del host y de origen, así como otros detalles.

.Pasos
. En ONTAP, cambie a. `advanced` nivel de privilegio.
+
[listing]
----
cluster::> set adv

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

cluster::*>
----
. Verifique que la cabina de origen se pueda ver en la controladora de destino.
+
[listing]
----
cluster::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
NET-1                    NETAPP_LUN_1   NETAPP              LUN

cluster::*> storage array config show -array-name NETAPP_LUN_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
ontaptme-fc-cluster-02
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
4 entries were displayed.

Warning: Configuration errors were detected.  Use 'storage errors show' for detailed information.
----
. Ver detalles sobre todos los errores de almacenamiento mostrados. Es posible que algunos errores requieran una acción antes de continuar. Sin embargo, los errores mostrados en el siguiente ejemplo, «'este dispositivo es una LUN de ONTAP(R)'». se puede ignorar con seguridad.
+
[NOTE]
====
El mensaje de error "este dispositivo es una LUN de ONTAP\(R\)". La causa es que FLI se basa en la tecnología de FlexArray que no admite la virtualización de los objetivos de ONTAP o ONTAP. Sin embargo, FLI puede importar las LUN; sin embargo, FlexArray no admite la virtualización de estas LUN.

====
+
[listing]
----
cluster::*> storage errors show
Disk: NET-1.1
UID: 60A98000:44306931:452B4738:5767366B:00000000:00000000:00000000:00000000:00000000:00000000
--------------------
NET-1.1 (60a9800044306931452b47385767366b): This device is an ONTAP(R) LUN.

Disk: NET-1.2
UID: 60A98000:44306931:452B4738:5767366D:00000000:00000000:00000000:00000000:00000000:00000000
--------------------
NET-1.2 (60a9800044306931452b47385767366d): This device is an ONTAP(R) LUN.

2 entries were displayed.
----
. Mostrar detalles de la LUN de origen.
+
[listing]
----
cluster::*> storage array config show -array-name NETAPP_LUN_1 -instance

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 1
        Array Target Ports: 500a0981880b813d
                 Initiator: 0d
                Array Name: NETAPP_LUN_1
   Target Side Switch Port: stme-5010-4:2-6
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 2

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 1
        Array Target Ports: 500a0981980b813d
                 Initiator: 0d
                Array Name: NETAPP_LUN_1
   Target Side Switch Port: stme-5010-4:2-5
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 2

~~~~~~ Output truncated ~~~~~~~
4 entries were displayed.

Warning: Configuration errors were detected.  Use 'storage errors show' for detailed information.
----
. Verifique que la cabina de origen se haya detectado a través de todos los puertos iniciadores.
+
[listing]
----
cluster::*> storage array config show -array-name NETAPP_LUN_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
ontaptme-fc-cluster-02
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
4 entries were displayed.

Warning: Configuration errors were detected.  Use 'storage errors show' for detailed information.
----
. Enumere las LUN asignadas del almacenamiento de 7-Mode. Compruebe las propiedades y rutas del disco.
+
[listing]
----
cluster::*> storage disk show -array-name NETAPP_LUN_1 -instance
                  Disk: NET-1.1
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: NETAPP_LUN_1
                Vendor: NETAPP
                 Model: LUN
         Serial Number: D0i1E+G8Wg6k
                   UID: 60A98000:44306931:452B4738:5767366B:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                                LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-6       ANO RDY  500a0981880b813d              1   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-5       AO  INU  500a0981980b813d              0   4 Gb/S             0             0
ontaptme-fc-cluster-01
                   0d             0  stme-5010-4:2-3       stme-5010-4:2-6       ANO RDY  500a0981880b813d              1   4 Gb/S             0             0
ontaptme-fc-cluster-01
                   0d             0  stme-5010-4:2-3       stme-5010-4:2-5       AO  INU  500a0981980b813d              0   4 Gb/S             0             0

Errors:
NET-1.1 (60a9800044306931452b47385767366b): This device is a ONTAP(R) LUN.
~~~~~~ Output truncated ~~~~~~~
2 entries were displayed.
----
. Compruebe que la LUN de origen esté marcada como externa.
+
[listing]
----
cluster::*> storage disk show -array-name NETAPP_LUN_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
NET-1.1                   -     -   - LUN     unassigned  -         -
NET-1.2                   -     -   - LUN     foreign     -         -
2 entries were displayed.
----
. Los números de serie se usan en los comandos de importación de la LUN FLI. Enumere todas las LUN externas y sus números de serie.
+
[listing]
----
cluster::*> storage disk show -container-type foreign -fields serial-number
disk    serial-number
------- --------------------------------
NET-1.2 D0i1E+G8Wg6m
----
. Cree la LUN de destino. La `LUN create` El comando detecta el tamaño y la alineación basados en la compensación de particiones y crea la LUN de manera acorde con el argumento Foreign-disk
+
[listing]
----
cluster::*> vol create -vserver fli_72C -volume flivol -aggregate aggr1 -size 10G
[Job 12523] Job succeeded: Successful
----
. Verificar volumen.
+
[listing]
----
cluster::*> vol show -vserver fli_72C
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
fli_72C   flivol       aggr1        online     RW         10GB     9.50GB    5%
fli_72C   rootvol      aggr1        online     RW          1GB    972.6MB    5%
2 entries were displayed.
----
. Cree la LUN de destino.
+
[listing]
----
cluster::*> lun create -vserver fli_72C -path /vol/flivol/72Clun1 -ostype windows_2008 -foreign-disk D0i1E+G8Wg6m

Created a LUN of size 3g (3224309760)
----
. Verificar la nueva LUN.
+
[listing]
----
cluster::*> lun show -vserver fli_72C
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli_72C   /vol/flivol/72Clun1             online  unmapped windows_2008
                                                                      3.00GB
----
. Cree un igroup de protocolo FCP con iniciadores de host.
+
[listing]
----
cluster::*> lun igroup create -vserver fli_72C -igroup 72C_g1 -protocol fcp -ostype windows –initiator 10:00:00:00:c9:e6:e2:79

cluster::*> lun igroup show -vserver fli_72C -igroup 72C_g1
          Vserver Name: fli_72C
           Igroup Name: 72C_g1
              Protocol: fcp
               OS Type: windows
Portset Binding Igroup: -
           Igroup UUID: 7bc184b1-dcac-11e4-9a88-00a0981cc318
                  ALUA: true
            Initiators: 10:00:00:00:c9:e6:e2:79 (logged in)
----
. Asigne el LUN de prueba al igroup de prueba.
+
[listing]
----
cluster::*> lun map -vserver fli_72C -path /vol/flivol/72Clun1 -igroup 72C_g1

cluster::*> lun mapping show -vserver fli_72C
Vserver    Path                                      Igroup   LUN ID  Protocol
---------- ----------------------------------------  -------  ------  --------
fli_72C    /vol/flivol/72Clun1                       72C_g1        0  fcp
----
. Desconectar la LUN de prueba.
+
[listing]
----
cluster::*> lun offline -vserver fli_72C -path /vol/flivol/72Clun1

Warning: This command will take LUN "/vol/flivol/72Clun1" in Vserver "fli_72C" offline.
Do you want to continue? {y|n}: y

cluster::*> lun show -vserver fli_72C
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli_72C   /vol/flivol/72Clun1             offline mapped   windows_2008
                                                                      3.00GB
----
. Crear relación de importación entre la nueva LUN y la LUN externa.
+
[listing]
----
cluster::*> lun import create -vserver fli_72C -path /vol/flivol/72Clun1 -foreign-disk D0i1E+G8Wg6m

cluster::*> lun import show -vserver fli_72C -path /vol/flivol/72Clun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
fli_72C D0i1E+G8Wg6m   /vol/flivol/72Clun1 import    stopped
                                                           stopped            0
----

