---
permalink: san-migration/task_fli_offline_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: Un trabajo de verificación es opcional, pero se recomienda. Es una comparación entre bloques de las LUN de origen y de destino. La verificación de las tareas tarda casi el mismo tiempo, o incluso un poco más, que el tiempo de migración. 
---
= Verificar los resultados de la migración sin conexión de ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tras migrar un LUN del arreglo externo a su sistema de almacenamiento ONTAP , FLI puede realizar una comparación bloque por bloque de los LUN de origen y destino para verificar que la migración sea completa y precisa. La verificación de la migración tarda aproximadamente el mismo tiempo (o un poco más) que la migración.

No es necesaria una verificación de migración, pero es muy recomendable.

.Acerca de esta tarea
A partir de ONTAP 9.17.1, la migración de datos de LUNs ajenos mediante migración FLI offline es compatible conlink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Sistemas ASA r2"^]. Los sistemas ASA r2 se diferencian de otros sistemas ONTAP (ASA, AFF y FAS) en la implementación de su capa de almacenamiento. de nombres). Cada volumen contiene solo una unidad de almacenamiento. Por lo tanto, en los sistemas ASA r2, no es necesario incluir el nombre del volumen en el...  `-path` opción al crear el LUN; debe incluir la ruta de la unidad de almacenamiento en su lugar.

.Pasos
. Iniciar la verificación de la migración de LUN.
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Este ejemplo muestra el comando para iniciar la verificación de migración de LUN para los LUN denominados *bootlun*, *fdrive* y *gdrive* en el volumen *winvol* y la SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----
. Supervisar el estado de verificación.
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, estimated-remaining-duration
----
+
Este ejemplo muestra el comando para monitorear el estado de verificación del SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration

vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
+
Puede ejecutar el mismo comando para seguir el progreso de la verificación. El estado operativo muestra el estado "completado" cuando la verificación se completa correctamente.

. Detener la verificación de LUN.
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Este ejemplo muestra el comando para detener la verificación de LUN para el SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
+
La verificación de importación de LUN debe detenerse explícitamente antes de volver a poner el LUN en línea. De lo contrario,  `lun online` El comando falla. Este paso debe realizarse manualmente incluso si el estado muestra que la verificación se ha completado.



.¿Que sigue?
link:remove-lun-import-relationship-offline.html["Eliminar la relación de importación de LUN"] .
