---
permalink: configure/fc-configure-adapter-initiator-mode.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Configura los adaptadores FC en modo iniciador para la migración con ONTAP Foreign LUN Import (FLI)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP FLI sobre FC requiere un adaptador FC en modo iniciador en el lado de ONTAP. Si no existen puertos de iniciador libres, es posible que tengas que convertir un puerto de adaptador objetivo FC a modo iniciador. Y si el adaptador FC tiene LIFs FC activas, entonces las LIFs FC activas deben moverse a puertos de adaptador diferentes dentro de la misma estructura.

.Pasos
. Ver los adaptadores FC disponibles:
+
[source, cli]
----
fcp adapter show -status-oper online
----
+
*Ejemplo de salida*

+
[listing]
----
  (network fcp adapter show)
                      Connection  Port    Admin    Operational
Node         Adapter  Established Address Status   Status          Topology
------------ -------- ----------- ------- -------- --------------- --------
ssan-a50-06a 3a       true        640a00  up       online          fabric
ssan-a50-06b 3b       true        640a00  up       online          fabric
ssan-a50-07a 3a       true        640e00  up       online          fabric
ssan-a50-07b 3b       true        640d00  up       online          fabric
----
. Desconecta el puerto del adaptador FC objetivo:
+
[source, cli]
----
fcp adapter modify -node <node_name> -adapter <adapter>> -status-admin down;
----
+
*Ejemplo de salida*

+
[listing]
----
fcp adapter modify -node ssan-a50-06a -adapter 3a -status-admin down;
----
. Comprueba que el estado del adaptador es down:
+
[source, cli]
----
fcp adapter show -node <node_name> -adapter <adapter>> -fields status-admin
----
+
*Ejemplo de salida*

+
[listing]
----
ssan-a50-06-07::*> fcp adapter show -node ssan-a50-06a -adapter 3a -fields status-admin

node         adapter status-admin
------------ ------- ------------
ssan-a50-06a 3a      down
----
. Convierte el puerto adaptador FC de modo objetivo a modo iniciador:
+
[source, cli]
----
system node hardware unified-connect modify -node <node_name> -adapter <adapter> -type initiator
----
+
*Ejemplo*

+
[listing]
----
ssan-a50-06-07::*> system node hardware unified-connect modify -node ssan-a50-06a -adapter 3a -type initiator

Any changes will take effect after rebooting the system. Use the "system node reboot" command to reboot.
----
. Vuelva a poner el adaptador en línea:
+
[source, cli]
----
fcp adapter modify -node <node_name> -adapter <adapter> -status-admin up;
----
+
*Ejemplo*

+
[listing]
----
ssan-a50-06-07::*> fcp adapter modify -node ssan-a50-06a -adapter 3a -status-admin up;
----
. Verifica que el adaptador vuelve a estar en línea y en modo iniciador:
+
[source, cli]
----
system node hardware unified-connect show
----
+
*Ejemplo*

+
[listing]
----
ssan-a50-06-07::*> system node hardware unified-connect show
                       Current  Current    Pending  Pending    Admin
Node          Adapter  Mode     Type       Mode     Type       Status
------------  -------  -------  ---------  -------  ---------  -----------
ssan-a50-06a  3a       fc       target     -        initiator  offline << pending node reboot
ssan-a50-06b  3b       fc       target     -        -          online
ssan-a50-07a  3c       fc       target     -        -          online
ssan-a50-07a  3d       fc       initiator  -        -          online <<< already converted
ssan-a50-06-07::*>
----

